openapi: 3.1.0
info:
  description: The PingOne Platform API covering the PingOne Verify service
  title: PingOne Platform API - PingOne Verify
  version: 2023-07-20
externalDocs:
  description: PingOne Platform API Reference - PingOne Verify APIs
  url: https://apidocs.pingidentity.com/pingone/platform/v1/api/#pingone-verify
servers:
- description: PingOne Platform API Endpoint
  url: "{protocol}://{baseDomain}.{suffix}/v1"
  variables:
    suffix:
      default: com
      enum:
      - asia
      - ca
      - com
      - com.au
      - eu
    baseDomain:
      default: api.pingone
    protocol:
      default: https
- description: PingOne Platform API Endpoint
  url: "{protocol}://{baseHostname}/v1"
  variables:
    baseHostname:
      default: api.pingone.com
    protocol:
      default: https
security:
- bearer: []
tags:
- name: Verify Policies
paths:
  /environments/{environmentID}/verifyPolicies:
    get:
      operationId: readAllVerifyPolicies
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/readAllVerifyPolicies_200_response'
          description: Successful response
      summary: READ All Verify Policies
      tags:
      - Verify Policies
      x-pingidentity-paginatedresponse: true
    post:
      operationId: createVerifyPolicy
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              name: Example Verify Policy
              default: false
              description: All types required
              email:
                createMfaDevice: true
                otp:
                  attempts:
                    count: 5
                  deliveries:
                    cooldown:
                      duration: 30
                      timeUnit: SECONDS
                    count: 3
                  lifeTime:
                    duration: 10
                    timeUnit: MINUTES
                  notification:
                    templateName: email_phone_verification
                verify: REQUIRED
              facialComparison:
                threshold: HIGH
                verify: REQUIRED
              governmentId:
                verify: REQUIRED
              liveness:
                threshold: HIGH
                verify: REQUIRED
              phone:
                createMfaDevice: true
                otp:
                  attempts:
                    count: 5
                  deliveries:
                    cooldown:
                      duration: 30
                      timeUnit: SECONDS
                    count: 3
                  lifeTime:
                    duration: 10
                    timeUnit: MINUTES
                  notification:
                    templateName: email_phone_verification
                verify: REQUIRED
              transaction:
                dataCollection:
                  timeout:
                    duration: 15
                    timeUnit: MINUTES
                dataCollectionOnly: false
                timeout:
                  duration: 30
                  timeUnit: MINUTES
            schema:
              $ref: '#/components/schemas/VerifyPolicy'
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "405":
          $ref: '#/components/responses/405'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyPolicy'
          description: Successful response
      summary: CREATE Verify Policy
      tags:
      - Verify Policies
  /environments/{environmentID}/verifyPolicies/{verifyPolicyID}:
    delete:
      operationId: deleteVerifyPolicy
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: verifyPolicyID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "204":
          description: Successful response
      summary: Delete Verify Policy
      tags:
      - Verify Policies
    get:
      operationId: readOneVerifyPolicy
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: verifyPolicyID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyPolicy'
          description: Successful response
      summary: READ One Verify Policy
      tags:
      - Verify Policies
    put:
      operationId: updateVerifyPolicy
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: verifyPolicyID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              default: false
              description: Verify Government ID and compare Selfie
              facialComparison:
                threshold: HIGH
                verify: REQUIRED
              governmentId:
                verify: REQUIRED
              liveness:
                threshold: HIGH
                verify: REQUIRED
              name: Identity Verification
            schema:
              $ref: '#/components/schemas/VerifyPolicy'
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyPolicy'
          description: Successful response
      summary: UPDATE Verify Policy
      tags:
      - Verify Policies
  /environments/{environmentID}/voicePhrases:
    get:
      operationId: readAllVoicePhrases
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/readAllVoicePhrases_200_response'
          description: Successful response
      summary: READ All Voice Phrases
      tags:
      - Voice Phrases
      x-pingidentity-paginatedresponse: true
    post:
      operationId: createVoicePhrase
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              displayName: Example Voice Phrase
            schema:
              $ref: '#/components/schemas/VoicePhrase'
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "405":
          $ref: '#/components/responses/405'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoicePhrase'
          description: Successful response
      summary: CREATE Voice Phrase
      tags:
      - Voice Phrases
  /environments/{environmentID}/voicePhrases/{voicePhraseID}:
    delete:
      operationId: deleteVoicePhrase
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voicePhraseID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "204":
          description: Successful response
      summary: Delete Voice Phrase
      tags:
      - Voice Phrases
    get:
      operationId: readOneVoicePhrase
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voicePhraseID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoicePhrase'
          description: Successful response
      summary: READ One Voice Phrase
      tags:
      - Voice Phrases
    put:
      operationId: updateVoicePhrase
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voicePhraseID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              displayName: Voice Phrase Name
            schema:
              $ref: '#/components/schemas/VoicePhrase'
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoicePhrase'
          description: Successful response
      summary: UPDATE Voice Phrase
      tags:
      - Voice Phrases
  /environments/{environmentID}/voicePhrases/{voicePhraseID}/contents:
    get:
      operationId: readAllVoicePhraseContents
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voicePhraseID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/readAllVoicePhraseContents_200_response'
          description: Successful response
      summary: READ All Voice Phrase Contents
      tags:
      - Voice Phrase Contents
      x-pingidentity-paginatedresponse: true
    post:
      operationId: createVoicePhraseContent
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voicePhraseID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              locale: en
              content: Design brilliant journeys to any digital desintation.
            schema:
              $ref: '#/components/schemas/VoicePhraseContents'
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "405":
          $ref: '#/components/responses/405'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoicePhraseContents'
          description: Successful response
      summary: CREATE Voice Phrase Content
      tags:
      - Voice Phrase Contents
  /environments/{environmentID}/voicePhrases/{voicePhraseID}/contents/{voiceContentsID}:
    delete:
      operationId: deleteVoicePhraseContent
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voicePhraseID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voiceContentsID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "204":
          description: Successful response
      summary: Delete Voice Phrase Content
      tags:
      - Voice Phrase Contents
    get:
      operationId: readOneVoicePhraseContent
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voicePhraseID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voiceContentsID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoicePhraseContents'
          description: Successful response
      summary: READ One Voice Phrase Content
      tags:
      - Voice Phrase Contents
    put:
      operationId: updateVoicePhraseContent
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voicePhraseID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: voiceContentsID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              locale: en
              content: Brilliant journeys to any digital destination.
            schema:
              $ref: '#/components/schemas/VoicePhraseContents'
      responses:
        "400":
          $ref: '#/components/responses/400'
        "401":
          $ref: '#/components/responses/401'
        "403":
          $ref: '#/components/responses/403'
        "404":
          $ref: '#/components/responses/404'
        "409":
          $ref: '#/components/responses/409'
        "429":
          $ref: '#/components/responses/429'
        "500":
          $ref: '#/components/responses/500'
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoicePhraseContents'
          description: Successful response
      summary: UPDATE Voice Phrase Content
      tags:
      - Voice Phrase Contents
components:
  responses:
    "400":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: "Invalid request received.  Malformed JSON, malformed HTTP request."
    "401":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Request failed due to authorization issue.
    "403":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Request failed due to authorization issue.
    "404":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Not found.
    "405":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: "Invalid request received.  Malformed JSON, malformed HTTP request."
    "409":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Conflict.
    "429":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Request was rate limited
    "500":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Uncaught error occurred.  Platform outage
  schemas:
    LinksHATEOAS:
      additionalProperties:
        $ref: '#/components/schemas/LinksHATEOAS_value'
      readOnly: true
      x-pingidentity-paginatedresponse-links: true
    EnumInspectionType:
      description: "A string that defines the mechanism used to authenticate a `governmentId`\
        \ document.  Options are `AUTOMATIC`, `MANUAL`, or `STEP_UP`."
      enum:
      - AUTOMATIC
      - MANUAL
      - STEP_UP
      type: string
    EnumProviderAuto:
      description: A string that defines the automatic verification subprocessor;
        can be `MITEK` or `VERIFF`.
      enum:
      - MITEK
      - VERIFF
      type: string
    EnumProviderManual:
      description: A string that defines the automatic verification subprocessor;
        can be `MITEK`.
      enum:
      - MITEK
      type: string
    EnumTimeUnit:
      description: A string that defines the time unit of a specified duration in
        `SECONDS` or `MINUTES`.
      enum:
      - SECONDS
      - MINUTES
      type: string
    EnumThreshold:
      description: "A string that defines the verification comparison threshold. Options\
        \ are `LOW`, `MEDIUM` and `HIGH`."
      enum:
      - LOW
      - MEDIUM
      - HIGH
      type: string
    EnumVerify:
      description: "A string that defines the verification check requirements. Options\
        \ are `REQUIRED`, `OPTIONAL` and `DISABLED`."
      enum:
      - REQUIRED
      - OPTIONAL
      - DISABLED
      type: string
    FacialComparisonConfiguration:
      example:
        verify: null
        threshold: LOW
      properties:
        verify:
          $ref: '#/components/schemas/EnumVerify'
        threshold:
          $ref: '#/components/schemas/EnumThreshold'
      required:
      - threshold
      - verify
    GovernmentIdConfiguration:
      example:
        provider:
          auto: MITEK
          manual: MITEK
        inspectionType: AUTOMATIC
        verify: REQUIRED
        failExpiredId: true
        retry:
          attempts: 5
      properties:
        failExpiredId:
          description: Indicates whether verification should fail if the ID is expired.
          type: boolean
        inspectionType:
          $ref: '#/components/schemas/EnumInspectionType'
        provider:
          $ref: '#/components/schemas/GovernmentIdConfiguration_provider'
        retry:
          $ref: '#/components/schemas/ObjectRetry'
        verify:
          $ref: '#/components/schemas/EnumVerify'
      required:
      - verify
    LivenessConfiguration:
      example:
        verify: null
        threshold: null
        retry:
          attempts: 5
      properties:
        retry:
          $ref: '#/components/schemas/ObjectRetry'
        threshold:
          $ref: '#/components/schemas/EnumThreshold'
        verify:
          $ref: '#/components/schemas/EnumVerify'
      required:
      - threshold
      - verify
    ObjectEnvironment:
      example:
        id: id
      properties:
        id:
          description: A string that specifies the environment associated with the
            object.
          readOnly: true
          type: string
      readOnly: true
    ObjectRetry:
      example:
        attempts: 5
      properties:
        attempts:
          description: The number of retries permitted.
          type: integer
    OTPDeviceConfiguration:
      example:
        createMfaDevice: true
        verify: null
        otp:
          notification:
            templateName: templateName
            variantName: variantName
          lifeTime:
            duration: 9
            timeUnit: null
          attempts:
            count: 5
          deliveries:
            count: 2
            cooldown:
              duration: 7
              timeUnit: SECONDS
      properties:
        verify:
          $ref: '#/components/schemas/EnumVerify'
        createMfaDevice:
          description: "When enabled, PingOne Verify registers the email address or\
            \ phone number with PingOne MFA as a verified MFA device."
          type: boolean
        otp:
          $ref: '#/components/schemas/OTPDeviceConfiguration_otp'
      required:
      - verify
    P1Error:
      example:
        code: code
        details:
        - code: code
          innerError:
            allowedValues:
            - allowedValues
            - allowedValues
            rangeMaximumValue: 6
            referencedValues:
            - referencedValues
            - referencedValues
            allowedPattern: allowedPattern
            maximumValue: 1
            rangeMinimumValue: 0
          message: message
          target: target
        - code: code
          innerError:
            allowedValues:
            - allowedValues
            - allowedValues
            rangeMaximumValue: 6
            referencedValues:
            - referencedValues
            - referencedValues
            allowedPattern: allowedPattern
            maximumValue: 1
            rangeMinimumValue: 0
          message: message
          target: target
        id: id
        message: message
      properties:
        id:
          description: "A unique identifier that is stored in log files and always\
            \ included in an error response. This value can be used to track the error\
            \ received by the client, with server-side activity included for troubleshooting\
            \ purposes."
          type: string
        code:
          description: A general fault code which the client must handle to provide
            all exception handling routines and to localize messages for users. This
            code is common across all PingOne services and is human readable (such
            as a defined constant rather than a number).
          type: string
        message:
          description: A short description of the error. This message is intended
            to assist with debugging and is returned in English only.
          type: string
        details:
          description: Additional details about the error. Optional information to
            help resolve the error and to display to users.
          items:
            $ref: '#/components/schemas/P1Error_details_inner'
          type: array
    TransactionConfiguration:
      example:
        dataCollectionOnly: true
        timeout:
          duration: 3
          timeUnit: null
        dataCollection:
          timeout:
            duration: 2
            timeUnit: null
      properties:
        timeout:
          $ref: '#/components/schemas/TransactionConfiguration_timeout'
        dataCollection:
          $ref: '#/components/schemas/TransactionConfiguration_dataCollection'
        dataCollectionOnly:
          type: boolean
    VoiceConfiguration:
      example:
        verify: null
        enrollment: true
        textDependent:
          samples: null
          phrase:
            id: id
        comparison:
          threshold: null
        liveness:
          threshold: null
        referenceData:
          retainOriginalRecordings: true
          updateOnReenrollment: true
          updateOnVerification: true
      properties:
        verify:
          $ref: '#/components/schemas/EnumVerify'
        enrollment:
          type: boolean
        textDependent:
          $ref: '#/components/schemas/VoiceConfigurationTextDependent'
        comparison:
          $ref: '#/components/schemas/VoiceConfigurationThreshold'
        liveness:
          $ref: '#/components/schemas/VoiceConfigurationThreshold'
        referenceData:
          $ref: '#/components/schemas/VoiceConfigurationReferenceData'
      required:
      - comparison
      - enrollment
      - liveness
      - verify
    VoiceConfigurationReferenceData:
      example:
        retainOriginalRecordings: true
        updateOnReenrollment: true
        updateOnVerification: true
      properties:
        retainOriginalRecordings:
          type: boolean
        updateOnReenrollment:
          type: boolean
        updateOnVerification:
          type: boolean
    VoiceConfigurationThreshold:
      example:
        threshold: null
      properties:
        threshold:
          $ref: '#/components/schemas/EnumThreshold'
      required:
      - threshold
    VoiceConfigurationTextDependentPhrase:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
    VoiceConfigurationTextDependent:
      example:
        samples: null
        phrase:
          id: id
      properties:
        samples:
          type: integer
        phrase:
          $ref: '#/components/schemas/VoiceConfigurationTextDependentPhrase'
      required:
      - phrase
      - samples
    VoicePhrase:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        environment:
          id: id
        displayName: displayName
        id: id
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          readOnly: true
          type: string
        environment:
          $ref: '#/components/schemas/ObjectEnvironment'
        displayName:
          type: string
        createdAt:
          format: date-time
          readOnly: true
          type: string
        updatedAt:
          format: date-time
          readOnly: true
          type: string
      required:
      - displayName
    VoicePhraseContents:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        environment:
          id: id
        id: id
        voicePhrase:
          id: id
        locale: locale
        content: content
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          readOnly: true
          type: string
        environment:
          $ref: '#/components/schemas/ObjectEnvironment'
        voicePhrase:
          $ref: '#/components/schemas/VoicePhraseContents_voicePhrase'
        locale:
          type: string
        content:
          type: string
        createdAt:
          format: date-time
          readOnly: true
          type: string
        updatedAt:
          format: date-time
          readOnly: true
          type: string
      required:
      - content
      - locale
      - voicePhrase
    VerifyPolicy:
      example:
        voice:
          verify: null
          enrollment: true
          textDependent:
            samples: null
            phrase:
              id: id
          comparison:
            threshold: null
          liveness:
            threshold: null
          referenceData:
            retainOriginalRecordings: true
            updateOnReenrollment: true
            updateOnVerification: true
        _links:
          key:
            href: https://openapi-generator.tech
        liveness:
          verify: null
          threshold: null
          retry:
            attempts: 5
        description: description
        createdAt: 2000-01-23T04:56:07.000+00:00
        environment:
          id: id
        default: true
        phone:
          createMfaDevice: true
          verify: null
          otp:
            notification:
              templateName: templateName
              variantName: variantName
            lifeTime:
              duration: 9
              timeUnit: null
            attempts:
              count: 5
            deliveries:
              count: 2
              cooldown:
                duration: 7
                timeUnit: SECONDS
        name: name
        facialComparison:
          verify: null
          threshold: LOW
        id: id
        email:
          createMfaDevice: true
          verify: null
          otp:
            notification:
              templateName: templateName
              variantName: variantName
            lifeTime:
              duration: 9
              timeUnit: null
            attempts:
              count: 5
            deliveries:
              count: 2
              cooldown:
                duration: 7
                timeUnit: SECONDS
        transaction:
          dataCollectionOnly: true
          timeout:
            duration: 3
            timeUnit: null
          dataCollection:
            timeout:
              duration: 2
              timeUnit: null
        governmentId:
          provider:
            auto: MITEK
            manual: MITEK
          inspectionType: AUTOMATIC
          verify: REQUIRED
          failExpiredId: true
          retry:
            attempts: 5
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        _links:
          additionalProperties:
            $ref: '#/components/schemas/LinksHATEOAS_value'
          readOnly: true
          x-pingidentity-paginatedresponse-links: true
        id:
          readOnly: true
          type: string
        environment:
          $ref: '#/components/schemas/ObjectEnvironment'
        name:
          description: Name displayed in PingOne Admin UI.
          type: string
        description:
          description: "Description displayed in PingOne Admin UI, 1-1024 characters."
          type: string
        default:
          description: Required as true to set this verify policy as the default policy
            for the environment; otherwise optional and defaults to false.
          type: boolean
        governmentId:
          $ref: '#/components/schemas/GovernmentIdConfiguration'
        facialComparison:
          $ref: '#/components/schemas/FacialComparisonConfiguration'
        liveness:
          $ref: '#/components/schemas/LivenessConfiguration'
        email:
          $ref: '#/components/schemas/OTPDeviceConfiguration'
        phone:
          $ref: '#/components/schemas/OTPDeviceConfiguration'
        transaction:
          $ref: '#/components/schemas/TransactionConfiguration'
        voice:
          $ref: '#/components/schemas/VoiceConfiguration'
        createdAt:
          format: date-time
          readOnly: true
          type: string
        updatedAt:
          format: date-time
          readOnly: true
          type: string
      required:
      - name
    readAllVerifyPolicies_200_response__embedded:
      example:
        verifyPolicies:
        - voice:
            verify: null
            enrollment: true
            textDependent:
              samples: null
              phrase:
                id: id
            comparison:
              threshold: null
            liveness:
              threshold: null
            referenceData:
              retainOriginalRecordings: true
              updateOnReenrollment: true
              updateOnVerification: true
          _links:
            key:
              href: https://openapi-generator.tech
          liveness:
            verify: null
            threshold: null
            retry:
              attempts: 5
          description: description
          createdAt: 2000-01-23T04:56:07.000+00:00
          environment:
            id: id
          default: true
          phone:
            createMfaDevice: true
            verify: null
            otp:
              notification:
                templateName: templateName
                variantName: variantName
              lifeTime:
                duration: 9
                timeUnit: null
              attempts:
                count: 5
              deliveries:
                count: 2
                cooldown:
                  duration: 7
                  timeUnit: SECONDS
          name: name
          facialComparison:
            verify: null
            threshold: LOW
          id: id
          email:
            createMfaDevice: true
            verify: null
            otp:
              notification:
                templateName: templateName
                variantName: variantName
              lifeTime:
                duration: 9
                timeUnit: null
              attempts:
                count: 5
              deliveries:
                count: 2
                cooldown:
                  duration: 7
                  timeUnit: SECONDS
          transaction:
            dataCollectionOnly: true
            timeout:
              duration: 3
              timeUnit: null
            dataCollection:
              timeout:
                duration: 2
                timeUnit: null
          governmentId:
            provider:
              auto: MITEK
              manual: MITEK
            inspectionType: AUTOMATIC
            verify: REQUIRED
            failExpiredId: true
            retry:
              attempts: 5
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - voice:
            verify: null
            enrollment: true
            textDependent:
              samples: null
              phrase:
                id: id
            comparison:
              threshold: null
            liveness:
              threshold: null
            referenceData:
              retainOriginalRecordings: true
              updateOnReenrollment: true
              updateOnVerification: true
          _links:
            key:
              href: https://openapi-generator.tech
          liveness:
            verify: null
            threshold: null
            retry:
              attempts: 5
          description: description
          createdAt: 2000-01-23T04:56:07.000+00:00
          environment:
            id: id
          default: true
          phone:
            createMfaDevice: true
            verify: null
            otp:
              notification:
                templateName: templateName
                variantName: variantName
              lifeTime:
                duration: 9
                timeUnit: null
              attempts:
                count: 5
              deliveries:
                count: 2
                cooldown:
                  duration: 7
                  timeUnit: SECONDS
          name: name
          facialComparison:
            verify: null
            threshold: LOW
          id: id
          email:
            createMfaDevice: true
            verify: null
            otp:
              notification:
                templateName: templateName
                variantName: variantName
              lifeTime:
                duration: 9
                timeUnit: null
              attempts:
                count: 5
              deliveries:
                count: 2
                cooldown:
                  duration: 7
                  timeUnit: SECONDS
          transaction:
            dataCollectionOnly: true
            timeout:
              duration: 3
              timeUnit: null
            dataCollection:
              timeout:
                duration: 2
                timeUnit: null
          governmentId:
            provider:
              auto: MITEK
              manual: MITEK
            inspectionType: AUTOMATIC
            verify: REQUIRED
            failExpiredId: true
            retry:
              attempts: 5
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        verifyPolicies:
          items:
            $ref: '#/components/schemas/VerifyPolicy'
          type: array
    readAllVerifyPolicies_200_response:
      example:
        size: 4.145608029883936
        _links:
          key:
            href: https://openapi-generator.tech
        _embedded:
          verifyPolicies:
          - voice:
              verify: null
              enrollment: true
              textDependent:
                samples: null
                phrase:
                  id: id
              comparison:
                threshold: null
              liveness:
                threshold: null
              referenceData:
                retainOriginalRecordings: true
                updateOnReenrollment: true
                updateOnVerification: true
            _links:
              key:
                href: https://openapi-generator.tech
            liveness:
              verify: null
              threshold: null
              retry:
                attempts: 5
            description: description
            createdAt: 2000-01-23T04:56:07.000+00:00
            environment:
              id: id
            default: true
            phone:
              createMfaDevice: true
              verify: null
              otp:
                notification:
                  templateName: templateName
                  variantName: variantName
                lifeTime:
                  duration: 9
                  timeUnit: null
                attempts:
                  count: 5
                deliveries:
                  count: 2
                  cooldown:
                    duration: 7
                    timeUnit: SECONDS
            name: name
            facialComparison:
              verify: null
              threshold: LOW
            id: id
            email:
              createMfaDevice: true
              verify: null
              otp:
                notification:
                  templateName: templateName
                  variantName: variantName
                lifeTime:
                  duration: 9
                  timeUnit: null
                attempts:
                  count: 5
                deliveries:
                  count: 2
                  cooldown:
                    duration: 7
                    timeUnit: SECONDS
            transaction:
              dataCollectionOnly: true
              timeout:
                duration: 3
                timeUnit: null
              dataCollection:
                timeout:
                  duration: 2
                  timeUnit: null
            governmentId:
              provider:
                auto: MITEK
                manual: MITEK
              inspectionType: AUTOMATIC
              verify: REQUIRED
              failExpiredId: true
              retry:
                attempts: 5
            updatedAt: 2000-01-23T04:56:07.000+00:00
          - voice:
              verify: null
              enrollment: true
              textDependent:
                samples: null
                phrase:
                  id: id
              comparison:
                threshold: null
              liveness:
                threshold: null
              referenceData:
                retainOriginalRecordings: true
                updateOnReenrollment: true
                updateOnVerification: true
            _links:
              key:
                href: https://openapi-generator.tech
            liveness:
              verify: null
              threshold: null
              retry:
                attempts: 5
            description: description
            createdAt: 2000-01-23T04:56:07.000+00:00
            environment:
              id: id
            default: true
            phone:
              createMfaDevice: true
              verify: null
              otp:
                notification:
                  templateName: templateName
                  variantName: variantName
                lifeTime:
                  duration: 9
                  timeUnit: null
                attempts:
                  count: 5
                deliveries:
                  count: 2
                  cooldown:
                    duration: 7
                    timeUnit: SECONDS
            name: name
            facialComparison:
              verify: null
              threshold: LOW
            id: id
            email:
              createMfaDevice: true
              verify: null
              otp:
                notification:
                  templateName: templateName
                  variantName: variantName
                lifeTime:
                  duration: 9
                  timeUnit: null
                attempts:
                  count: 5
                deliveries:
                  count: 2
                  cooldown:
                    duration: 7
                    timeUnit: SECONDS
            transaction:
              dataCollectionOnly: true
              timeout:
                duration: 3
                timeUnit: null
              dataCollection:
                timeout:
                  duration: 2
                  timeUnit: null
            governmentId:
              provider:
                auto: MITEK
                manual: MITEK
              inspectionType: AUTOMATIC
              verify: REQUIRED
              failExpiredId: true
              retry:
                attempts: 5
            updatedAt: 2000-01-23T04:56:07.000+00:00
        count: 7.386281948385884
      properties:
        _links:
          additionalProperties:
            $ref: '#/components/schemas/LinksHATEOAS_value'
          readOnly: true
          x-pingidentity-paginatedresponse-links: true
        _embedded:
          $ref: '#/components/schemas/readAllVerifyPolicies_200_response__embedded'
        size:
          type: number
        count:
          type: number
      x-pingidentity-paginatedresponse: true
    readAllVoicePhrases_200_response__embedded:
      example:
        voicePhrases:
        - createdAt: 2000-01-23T04:56:07.000+00:00
          environment:
            id: id
          displayName: displayName
          id: id
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - createdAt: 2000-01-23T04:56:07.000+00:00
          environment:
            id: id
          displayName: displayName
          id: id
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        voicePhrases:
          items:
            $ref: '#/components/schemas/VoicePhrase'
          type: array
    readAllVoicePhrases_200_response:
      example:
        size: 0.8008281904610115
        _links:
          key:
            href: https://openapi-generator.tech
        _embedded:
          voicePhrases:
          - createdAt: 2000-01-23T04:56:07.000+00:00
            environment:
              id: id
            displayName: displayName
            id: id
            updatedAt: 2000-01-23T04:56:07.000+00:00
          - createdAt: 2000-01-23T04:56:07.000+00:00
            environment:
              id: id
            displayName: displayName
            id: id
            updatedAt: 2000-01-23T04:56:07.000+00:00
        count: 6.027456183070403
      properties:
        _links:
          additionalProperties:
            $ref: '#/components/schemas/LinksHATEOAS_value'
          readOnly: true
          x-pingidentity-paginatedresponse-links: true
        _embedded:
          $ref: '#/components/schemas/readAllVoicePhrases_200_response__embedded'
        size:
          type: number
        count:
          type: number
      x-pingidentity-paginatedresponse: true
    readAllVoicePhraseContents_200_response__embedded:
      example:
        contents:
        - createdAt: 2000-01-23T04:56:07.000+00:00
          environment:
            id: id
          id: id
          voicePhrase:
            id: id
          locale: locale
          content: content
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - createdAt: 2000-01-23T04:56:07.000+00:00
          environment:
            id: id
          id: id
          voicePhrase:
            id: id
          locale: locale
          content: content
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        contents:
          items:
            $ref: '#/components/schemas/VoicePhraseContents'
          type: array
    readAllVoicePhraseContents_200_response:
      example:
        size: 0.8008281904610115
        _links:
          key:
            href: https://openapi-generator.tech
        _embedded:
          contents:
          - createdAt: 2000-01-23T04:56:07.000+00:00
            environment:
              id: id
            id: id
            voicePhrase:
              id: id
            locale: locale
            content: content
            updatedAt: 2000-01-23T04:56:07.000+00:00
          - createdAt: 2000-01-23T04:56:07.000+00:00
            environment:
              id: id
            id: id
            voicePhrase:
              id: id
            locale: locale
            content: content
            updatedAt: 2000-01-23T04:56:07.000+00:00
        count: 6.027456183070403
      properties:
        _links:
          additionalProperties:
            $ref: '#/components/schemas/LinksHATEOAS_value'
          readOnly: true
          x-pingidentity-paginatedresponse-links: true
        _embedded:
          $ref: '#/components/schemas/readAllVoicePhraseContents_200_response__embedded'
        size:
          type: number
        count:
          type: number
      x-pingidentity-paginatedresponse: true
    LinksHATEOAS_value:
      example:
        href: https://openapi-generator.tech
      properties:
        href:
          description: The HREF of the link.
          format: uri
          type: string
      required:
      - href
    GovernmentIdConfiguration_provider:
      example:
        auto: MITEK
        manual: MITEK
      properties:
        auto:
          $ref: '#/components/schemas/EnumProviderAuto'
        manual:
          $ref: '#/components/schemas/EnumProviderManual'
    OTPDeviceConfiguration_otp_attempts:
      description: OTP attempts configuration.
      example:
        count: 5
      properties:
        count:
          description: Count of OTP failures.
          type: integer
      required:
      - count
    OTPDeviceConfiguration_otp_deliveries_cooldown:
      description: Cooldown (waiting period between OTP attempts) configuration.
      example:
        duration: 7
        timeUnit: SECONDS
      properties:
        duration:
          description: Cooldown duration configuration.
          type: integer
        timeUnit:
          $ref: '#/components/schemas/EnumTimeUnit'
      required:
      - duration
      - timeUnit
    OTPDeviceConfiguration_otp_deliveries:
      description: OTP delivery configuration.
      example:
        count: 2
        cooldown:
          duration: 7
          timeUnit: SECONDS
      properties:
        count:
          description: Count of OTP deliveries.
          type: integer
        cooldown:
          $ref: '#/components/schemas/OTPDeviceConfiguration_otp_deliveries_cooldown'
      required:
      - cooldown
      - count
    OTPDeviceConfiguration_otp_lifeTime:
      description: The length of time for which the OTP is valid.
      example:
        duration: 9
        timeUnit: null
      properties:
        duration:
          description: OTP duration configuration.
          type: integer
        timeUnit:
          $ref: '#/components/schemas/EnumTimeUnit'
      required:
      - duration
      - timeUnit
    OTPDeviceConfiguration_otp_notification:
      description: OTP notification template configuration.
      example:
        templateName: templateName
        variantName: variantName
      properties:
        templateName:
          type: string
        variantName:
          type: string
      required:
      - templateName
    OTPDeviceConfiguration_otp:
      example:
        notification:
          templateName: templateName
          variantName: variantName
        lifeTime:
          duration: 9
          timeUnit: null
        attempts:
          count: 5
        deliveries:
          count: 2
          cooldown:
            duration: 7
            timeUnit: SECONDS
      properties:
        attempts:
          $ref: '#/components/schemas/OTPDeviceConfiguration_otp_attempts'
        deliveries:
          $ref: '#/components/schemas/OTPDeviceConfiguration_otp_deliveries'
        lifeTime:
          $ref: '#/components/schemas/OTPDeviceConfiguration_otp_lifeTime'
        notification:
          $ref: '#/components/schemas/OTPDeviceConfiguration_otp_notification'
      required:
      - attempts
      - deliveries
      - lifeTime
      - notification
    P1Error_details_inner_innerError:
      description: Additional details to help the client developer resolve the fault
        (primarily for UI validation reasons).
      example:
        allowedValues:
        - allowedValues
        - allowedValues
        rangeMaximumValue: 6
        referencedValues:
        - referencedValues
        - referencedValues
        allowedPattern: allowedPattern
        maximumValue: 1
        rangeMinimumValue: 0
      properties:
        rangeMinimumValue:
          description: Errors that failed due to range violation. This attribute represents
            the minimum value of the range.
          type: integer
        rangeMaximumValue:
          description: The maximum range or value of an attribute.
          type: integer
        allowedPattern:
          description: A regex pattern describing an acceptable input pattern.
          type: string
        allowedValues:
          description: A list describing acceptable values.
          items:
            type: string
          type: array
        maximumValue:
          description: The maximum value allowed for the request.
          type: integer
        referencedValues:
          items:
            type: string
          type: array
    P1Error_details_inner:
      example:
        code: code
        innerError:
          allowedValues:
          - allowedValues
          - allowedValues
          rangeMaximumValue: 6
          referencedValues:
          - referencedValues
          - referencedValues
          allowedPattern: allowedPattern
          maximumValue: 1
          rangeMinimumValue: 0
        message: message
        target: target
      properties:
        code:
          description: A general fault code which the client must handle to provide
            all exception handling routines and to localize messages for users. This
            code is common across all PingOne services and is human readable (such
            as a defined constant rather than a number).
          type: string
        target:
          description: The item that caused the error (such as a form field ID or
            an attribute inside a JSON object).
          type: string
        message:
          description: A short description of the error. This message is intended
            to assist with debugging and is returned in English only.
          type: string
        innerError:
          $ref: '#/components/schemas/P1Error_details_inner_innerError'
    TransactionConfiguration_timeout:
      example:
        duration: 3
        timeUnit: null
      properties:
        duration:
          description: Length of time before transaction timeout expires; range is
            0-30 minutes or 0-1800 seconds.
          type: integer
        timeUnit:
          $ref: '#/components/schemas/EnumTimeUnit'
      required:
      - duration
      - timeUnit
    TransactionConfiguration_dataCollection_timeout:
      example:
        duration: 2
        timeUnit: null
      properties:
        duration:
          description: Length of time before data collection timeout expires; range
            is 0-30 minutes or 0-1800 seconds.
          type: integer
        timeUnit:
          $ref: '#/components/schemas/EnumTimeUnit'
      required:
      - duration
      - timeUnit
    TransactionConfiguration_dataCollection:
      example:
        timeout:
          duration: 2
          timeUnit: null
      properties:
        timeout:
          $ref: '#/components/schemas/TransactionConfiguration_dataCollection_timeout'
      required:
      - timeout
    VoicePhraseContents_voicePhrase:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
  securitySchemes:
    bearer:
      bearerFormat: JWT
      description: OAuth bearer token (see documentation)
      scheme: bearer
      type: http
